name: PySE CI

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Build Docker image
        run: |
          docker build -t transientskp/pyse .
      - name: Run nosetests
        run: |
          docker run transientskp/pyse nosetests --with-coverage --cover-package=sourcefinder
      - name: Run nosetests3
        run: |
          docker run transientskp/pyse nosetests3
      - name: Run pyse
        run: |
          docker run transientskp/pyse pyse --detection 5 --radius 400 --csv --force-beam  test/data/GRB120422A-120429.fits
